// This file is automatically generated by SCons
// DO NOT EDIT THIS FILE
#include "/opt/nsis-src/Source/tchar.h"
#define NSIS_PACKEDVERSION _T("0x03010666")
#define NSIS_VERSION _T("v29-Aug-2025.cvs")
