name: Build FPM

on:
  workflow_call:
    outputs:
      artifactName:
        description: "FPM artifacts"
        value: fpm-artifacts

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, i386, arm64/v8]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with: { submodules: true }
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with: { version: 9.4.0 }
      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
        with: { node-version: '22' }
      - name: Install dependencies & build (${{ matrix.arch }})
        run: |
          pnpm i --frozen-lockfile
          export ARCH=${{ matrix.arch }}
          bash build-linux.sh
          echo "ARCH_KEY=$(echo $ARCH | tr '/' '-')" >> $GITHUB_ENV
      - name: Upload FPM Linux artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: fpm-linux-${{ env.ARCH_KEY }}
          path: packages/fpm/out
          if-no-files-found: error
          retention-days: 1

  mac:
    runs-on: ${{ matrix.node }}
    strategy:
      matrix:
        node: [macos-13, macos-15]
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with: { submodules: true }
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with: { version: 9.4.0 }
      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
        with: { node-version: '22' }
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build for macOS
        run: bash packages/fpm/build.sh
        shell: bash
        env: { OS_TARGET: darwin }
      - name: Upload FPM macOS artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: fpm-mac-${{ matrix.node }}
          path: packages/fpm/out
          if-no-files-found: error
          retention-days: 1
